# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_clk.xdc

# IP: ip/bucket_row_2/bucket_row_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bucket_row_2 || ORIG_REF_NAME==bucket_row_2} -quiet] -quiet

# IP: ip/bucket_row_3/bucket_row_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bucket_row_3 || ORIG_REF_NAME==bucket_row_3} -quiet] -quiet
