# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/vivado_projects/sketch_network_measurement/sketch_network_measurement.srcs/sources_1/ip/bucket_row_1/bucket_row_1.xci
# IP: The module: 'bucket_row_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado_projects/sketch_network_measurement/sketch_network_measurement.gen/sources_1/ip/bucket_row_1/bucket_row_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bucket_row_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/vivado_projects/sketch_network_measurement/sketch_network_measurement.srcs/sources_1/ip/bucket_row_1/bucket_row_1.xci
# IP: The module: 'bucket_row_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado_projects/sketch_network_measurement/sketch_network_measurement.gen/sources_1/ip/bucket_row_1/bucket_row_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bucket_row_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
